### ISSUE TITLE
Blinking test_full

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#92] opened 2020-03-02 13:11 UTC
Seems to fail often on Linux, but sometimes also on Windows: https://travis-ci.org/ActivityWatch/activitywatch/jobs/657063999#L2820-L2821

Occurred frequently in this PR, with attempted fixes: https://github.com/ActivityWatch/activitywatch/pull/356

**Comment by johan-bjareholt** [comment] 2020-03-03 21:27
I've ran this for an hour on my local machine and it has failed once, not sure what the issue can be really.
But at least it is possible to reproduce.

**Comment by xylix** [comment] 2020-03-04 13:25
Could it be related to the hard coded test port being in use on travis? Or
related to ram limits.

I've no other idea what could it be.

**Comment by johan-bjareholt** [comment] 2020-03-04 14:35
@xylix I've also considered if it's relate dto the hard-coded port, but then realized that the test is only run once and inside a container so it really shouldn't interfere with anything else.

I've also considered if it's because we don't cleanly shut down, but it's the same thing there that the test runs once and inside a container so it shouldn't interfere. I'd like to fix this anyway though but it will be almost impossible before rocket releases version 0.5 with its async support and updated hyper where it should be possible to gracefully shut down.

**Comment by xylix** [comment] 2020-03-06 06:34
Looking some more at aw-server-rust's aw-client, running the tests in my ubuntu virtual machine until failure,
`// Start testserver and wait 10s for it to start up // TODO: Properly shutdown`

I don't think the test_full is actually waiting 10 seconds. Could the problem just be it trying to get stuff from the setup server before the server is ready?

**Comment by johan-bjareholt** [comment] 2020-03-06 17:46
Well done!

> Looking into it now I'm starting to think most likely the server is closing the connection between the get_bucket and get_buckets call in the test_full. If this is the case it's not really a problem with the test, it's problem with the client / reqwest timing out. It's not even a long session so this shouldn't happen.

Well, the proper thing to do would be to figure out why the server is closing the connection.
Can't really see a reason why this would occur.

> What are the planned use cases for aw-client-rust anyway? If it's stuff like the watchers that might update every heartbeat or much slower does it even make sense to keep a connection alive or should we just send single requests with the client?

For now it's just integration tests and my prototype aw-watcher-wayland. In the future it would be nice if it could be a proper client library but I don't think we should prioritize doing that now.

**Comment by xylix** [comment] 2020-03-06 17:55
Yeah. Rocket supports an option for keep-alive, will probably need to try a longer option for that at least. Altough the default probably isn't 0 anyway.

But looking at the code it doesn't seem like aw-server-rust handles a cut connection in any way since it only initializes the reqwest client once. Or does reqwest automatically re-connect on demand?

**Comment by johan-bjareholt** [comment] 2020-03-06 18:16
@xylix The default keep_alive seems to be 5 seconds

https://api.rocket.rs/v0.4/src/rocket/config/config.rs.html#231

**Comment by xylix** [comment] 2020-03-07 07:18
Explicitly setting it to 10 or 20 seconds did nothing :/. 

An explanation that would make sense would be rocket dropping connections on high cpu usage / low available cpu resources, since in my VM and travis it happens quite often but you earlier said it took almost an hour of running tests to get one failure.

**Comment by xylix** [comment] 2020-03-08 07:22
Upstream suggested we wait for Rocket 0.5 and see if it's fixed in that. 

They mentioned possible solutions including setting keep_alive to 0 and running rocket behind a reverse proxy.

@johan-bjareholt So we should probably just set the keep_alive to 0 for now as a workaround, and then get back to this when rocket 0.5 releases.

**Comment by xylix** [comment] 2020-03-08 15:48
I created  https://github.com/ActivityWatch/aw-server-rust/pull/97 , but we should still leave this issue open until the upstream fix is confirmed / denied.

**Comment by johan-bjareholt** [comment] 2020-07-08 06:18
Has not occurred for a long time, not sure if it was because of one of our workarounds or the switch to GitHub actions though.

Closing

**Closed by johan-bjareholt** 2020-07-08 06:18 UTC
